### ISSUE TITLE
TODO: Before Publishing

### ISSUE THREAD

**Issue by Mandy-cyber** [Big-Sister-App/Big-Sister#1]
**An ongoing list of things to do (i.e. change) in the code before it gets published:**

- [ ] Turn debug off
- [ ] Change all show_result and/or dry_run parameters to False
- [ ] Run bfg on repo
- [ ] Complete run-through for formatting and cleaning
- [ ] Finish connecting to [heroku](https://www.honeybadger.io/blog/flask-github-actions-continuous-delivery/)
