### ISSUE TITLE
Functionality to let user choose frequency of alert emails pt2 (backend)

### ISSUE THREAD

**Issue by Mandy-cyber** [Big-Sister-App/Big-Sister#13]
> This ticket is the second part of [this ticket](#11).  This ticket cannot be completed until the other has been completed, so keep in touch with @kernadrews to check progress. 

**Context:**
Now that the database of emails includes an additional field for `emailFrequency` this has to now be reflected in the email sender.

**To-do:**
- [ ] Separate the emails in the database into **4 csv files** that correspond to the 4 emailFrequency options.
   - These files should be updated every time a new person joins the mailing list
- [ ] Either create 4 separate scripts that abstract from one file, and send out emails at different times, or some other solution you can think of.
- [ ] Test with dummy emails in the 4 files

**Useful Resource:**
A potential solution could utilize something called [cron](https://cloud.google.com/scheduler/docs/configuring/cron-job-schedules) that can schedule scripts to run at certain times everyday.
