### ISSUE TITLE
Add customization to Map

### ISSUE THREAD

**Issue by Mandy-cyber** [Big-Sister-App/Big-Sister#17]
> This is a continuation of [this ticket](#5) and [this merge]( #16) .

**Context:**
Currently our Map utilizes the bare minimum amount of customization and fields that the Google Maps API provides. For example, currently the report description is not shown, only the report type. Ideally, our map would include those details plus aesthetic changes to be outlined below:

**To-do:**
- [x] Add field for `reportDescription` in marker. If, for some reason, this is not possible then we may consider having the markers trigger popups with the report description.
- [x] Change the color of the marker depending on the report type
   - Would be even epicer if @alaatamam or @raabyo were to make custom pins for the different report types. But totally optional, no stress.

- [x] Change the map center to be closer to the marker that is clicked, and then zoom back out to the original zoom when report closed.
