### ISSUE TITLE
Implement Data Anonymization or Redaction for sensitive information

### ISSUE THREAD

**Issue by Mandy-cyber** [Big-Sister-App/Big-Sister#28]
> Loosely-related to #8 

**Context:**
Currently, when a user writes a report they are able to input sensitive information and it will not be filtered out, redacted, or anonymized. Whilst one would hope a user using a platform anonymously would _act_ anonymously, that's not how the internet works. As such, we need to develop a method to automatically anonymize/redact sensitive information from reports _before_ they get published.

**To-do:**
- [ ] Research different methods of data anonymization and redaction
   - Determine whether data anonymization or redaction is the best way forward. State why.
- [ ] Create a `Cleaner` class to house all 'cleaning' methods of the site (i.e. filters, redacters, anonymizers).
- [ ] Write and implement a cleaning method for the aforementioned report data.
