### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by Mandy-cyber** [Big-Sister-App/Big-Sister#30]
**Context:**
Currently, the website only looks good on laptops, and even then only within a certain range. What we want is for the website to look good, aka be responsive, to larger screens, laptops, tablets, and phones.

**To-do:**
- [ ] Make all pages of the website responsive.
- [ ] Test that it is responsive by running the website on different devices and/or using VSCode extensions such as **`MobileView`**
- [ ] Attach photos and/or videos of the responsive design when submitting this ticket.

**Useful Resources:**
[Mobile-first web design](https://www.uxpin.com/studio/blog/a-hands-on-guide-to-mobile-first-design/)
[HTML Responsive Web Design](https://www.w3schools.com/html/html_responsive.asp)
[Responsive Web Design](https://www.freecodecamp.org/news/responsive-web-design-modern-website-code-for-beginners/)
