### ISSUE TITLE
Use JSON formatting for report data

### ISSUE THREAD

**Issue by Mandy-cyber** [Big-Sister-App/Big-Sister#5]
**To-do:**
- [x] In `map.py` create json file of report data after lat/long pairs have been created. 
   - First make dataframe of info and use panda's `to_json()` method 
- [x] Change map.js to TypeScript file.
- [x] Make `getJson()` function that returns an array of objects of the report data
- [x] Make `createMarker()` function and call .forEach() in initMap() for getJson() return

**Future Plan:**
- Make cache of json data so we don't have to remake the json file every time a report is made

**Comment by Mandy-cyber** [comment]
Works with dummy data but will run it all again when report form is made and integrated with the back-end.
