### ISSUE TITLE
Remove harmful terminology from report descriptions

### ISSUE THREAD

**Issue by Mandy-cyber** [Big-Sister-App/Big-Sister#8]
**Context:**
Currently in the code the only thing we are filtering in the report data is the type of report. This should not be the case since `typeOfReport` will always have a finite number of options. Instead we need to be filtering reportDesc.

**To-do:**
- [ ] Create a list of harmful language that we do not want to accept in reports  (e.g. racist, homophobic, etc terminology) .
   - Once this is done, comment on this same issue with the list you've come up with
- [ ] Create a filter function that looks for, and removes, those harmful terms from a given report

**Considerations:**
- [ ] Should a report not be allowed to go through if it has more than x% of harmful language?
- [ ] Are we allowing swear words? If so, are we allowing all or just some?

**Comment by psefia** [comment]
In terms of filtering, what are the ethical implications of filtering out a true story that had derogatory words / keeping a fake story that avoided using derogatory words? Maybe we should have a "flag" button for extra user safety (on top of the baseline derogatory words filtering) that allows users to flag reports that sound/are messed up. They can get sent to us, and we can evaluate it. 

Also maybe instead of percentages, the filtering should just determine an x amount of times a certain derogatory word shows up in the report. We could have a tier list too, like 
- Removed when seen once: racist/homophobic terminology
- Removed when seen twice: words like "hate", "suffer", "kill", etc
- Removed when seen 3 times: swear words

**Comment by Mandy-cyber** [comment]
Really great points, I agree! My only concern is with the tier list that might be a whole other bunch of code to implement. I definitely agree with that tier 1, we should for sure just remove as soon as we see it, but for the other two we can maybe just add a "Trigger Warning" in front of the report that says that the following report contains mentions of xyz. What are your thoughts on that?

**Comment by Mandy-cyber** [comment]
If the filtering and adding 'Trigger Warning' is done right as the report is made, the users and us really shouldn't experience any noticeable delay. Runtime would only be a serious concern (in my understanding) if either the report or our lists of terminologies, were long.
